gpus: '0'
output_dir: 'output'
log_dir: 'log'
num_workers: 32
print_freq: 100
token_window_size: &tws 15
train_stage: 2 # Only stage 2

MODEL:
  out_kp: 15
  out_chns: 2
  window: *tws
  depth: 8
  heads: 8
  embedding: 'GCNEncoder'
  EMB_ARGS:
    arch: [[2, 8], [8, 16]]
    token_window_size: *tws
    out_features: 64

DATASET:
  train_dataset: 'nturgbd'
  test_dataset: 'nturgbd'
  root: '/mnt/DATASETS_RAID_28TB/nturgbd/'
  window_size: 300
  frame_interval: 1
  token_window_size: *tws
  add_cls: True
  mix_chance: 0.0
  mask_chance: 0.3
  stride: 1
  test_subset: 'validation'
  train_subset: 'train'
  rootIDX: 1
  camera_num: 10

  # Heatmap Generator
  Heatmap_Generator:
    use_gaussian_score: false
    with_limb: true
    with_kp: false
    heatmap_size: &hms 256 # HeatMap Size

LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  batch_size: 8
  shuffle: True
  end_epoch: 15
  resume: true
  optimizer: adam
  lr: 0.00001
  num_workers: 4
TEST:
  batch_size: 8
  num_workers: 2

DEBUG:
  DEBUG: true
