GPUS: '0'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 32
PRINT_FREQ: 100

MODEL:
  hidden: 30
  attn_heads: 5
  n_layers: 8

DATASET:
  TRAIN_DATASET: 'nturgbd'
  TEST_DATASET: 'nturgbd'
  ROOT: '/mnt/DATASETS_RAID_28TB/nturgbd/'
  WINDOW_SIZE: 300
  STRIDE: 1
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX: 2
  CAMERA_NUM: 10
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 256
  SHUFFLE: True
  END_EPOCH: 30
  RESUME: true
  OPTIMIZER: adam
  LR: 0.00001
TEST:
  BATCH_SIZE: 128
DEBUG:
  DEBUG: true
