gpus: '0'
output_dir: 'output'
log_dir: 'log'
num_workers: 32
print_freq: 100

MODEL:
  out_kp: 15
  out_chns: 2
  window: 10
  depth: 4
  heads: 8
  embedding: 'GCNEncoder'
  EMB_ARGS:
    arch: [[2, 8], [8, 16]]
    token_window_size: 10
    out_features: 64

DATASET:
  train_dataset: 'panoptic'
  test_dataset: 'panoptic'
  root: '/mnt/DATASETS_RAID_28TB/panoptic-toolbox/data/'
  window_size: &ws 300
  stride: 1
  test_subset: 'validation'
  train_subset: 'train'
  rootIDX: 1
  camera_num: 10

TRAIN:
  batch_size: 512
  shuffle: True
  end_epoch: 15
  resume: true
  optimizer: adam
  lr: 0.00001
  num_workers: 24

TEST:
  batch_size: 256
  num_workers: 8
  
DEBUG:
  DEBUG: true
