
# Training settings
epochs: 15
#Not used for `triangular2` cyclic!
lr_decay: 0.99
anneal_rate: 0.000001 # Temperature annealing rate
base_learning_rate: 1.0e-8
max_learning_rate: 1.0e-4
coeff_step_size_up: 1
coeff_step_size_down: 10
weight_decay: 0.05 # Learning rate decay
starting_temp: 1.0 # Starting temperature
temp_min: 0.5 # Minimum temperature to anneal to
num_images_save: 4 # Number of images to save
batch_size: 16
device: 'cuda'
world_size: 2
num_workers: 16

#NOTE: Not sure what it is.
transparent: true 

deepspeed: true
distributed_backend: true

# Dataset Settings
DATASET:
  train_dataset: 'ntu_mmcv'
  test_dataset: 'ntu_mmcv'
  window_size: &dws 48 # Dataset Window Size
  second_heatmap_size: &dVAE_heatmap_size null
  num_classes: 120
  mmcv_config: 'configs/nturgbd/ntu120_limb_xsub.py'

  Heatmap_Generator:
    # You need to also update `mmcv_config` if you change this value to something else.
    heatmap_size: 256


Pretrained_Models:
  discrete_vae_weight_path: ''
  pretrain_saved_file: './saved_models/beit_best_leafy-yogurt-1.pt'


PeIT:
  finetune_checkpoint: ''
  checkpoint_root_folder: './saved_models/'
  custom_run_name: 'NTU_RUN6_PreTrained_Learning_Leafy_Yogurt_15Epoch'
  window_size:
    - 0
    - 0
  num_mask_patches: 204
  max_mask_patches_per_block: null
  min_mask_patches_per_block: 16