# Training settings
epochs: 50
#Not used for `triangular2` cyclic!
lr_decay: 0.99
anneal_rate: 0.000001 # Temperature annealing rate
base_learning_rate: 1.0e-8
max_learning_rate: 1.0e-4
coeff_step_size_up: 5
coeff_step_size_down: 45
weight_decay: 0.0003
starting_temp: 1.0 # Starting temperature
temp_min: 0.5 # Minimum temperature to anneal to
num_images_save: 4 # Number of images to save
batch_size: &bs 16
device: "cuda"
world_size: 1
num_workers: 8
repeated_size_of_dataset: 10
extra_project_name: "sub120"

#NOTE: Not sure what it is.
transparent: true

deepspeed: true
distributed_backend: true

# Dataset Settings
DATASET:
  train_dataset: "ntu_mmcv"
  test_dataset: "ntu_mmcv"
  window_size: &dws 48 # Dataset Window Size
  second_heatmap: &dVAE_heatmap_size null
  num_classes: 120
  joint_number: &jn 17
  mmcv_config: "configs/nturgbd/ntu120_limb_xsub.py"

  Heatmap_Generator:
    # You need to also update `mmcv_config` if you change this value to something else.
    heatmap_size: 72
    joint_reduction: &cj false

Pretrained_Models:
  discrete_vae_weight_path: ""
  pretrain_saved_file: "/mnt/DATASETS_RAID_28TB/saved_models/current/RUN1_3DdVAE_HEATMAP_BASE_3DResBlock_Super_Serenity/beit_best_firm-wood-3_pretraining.pt"

PeIT:
  model: "beit_base"
  finetune_checkpoint: ""
  checkpoint_root_folder: "/mnt/DATASETS_RAID_28TB/saved_models/current"
  custom_run_name: "NTU120_SUB_RUN1"
  embed_2dpatch: *cj
  drop_rate: 0.6
  attn_drop_rate: 0.6
  drop_path_rate: 0.6
  patch_size: 4
  window_size:
    - 0
    - 0
  num_mask_patches: 204
  max_mask_patches_per_block: null
  min_mask_patches_per_block: 16
