
# Training settings
epochs: 30
#Not used for `triangular2` cyclic!
lr_decay: 0.999994
anneal_rate: 1.0e-7 # Temperature annealing rate
base_learning_rate: 5.0e-8
max_learning_rate: 1.0e-3
coeff_step_size_up: 1
coeff_step_size_down: 5
weight_decay: 0.05 # Learning rate decay
starting_temp: 5.0 # Starting temperature
temp_min: 0.5 # Minimum temperature to anneal to
num_images_save: 4 # Number of images to save
batch_size: 8
device: 'cuda'
world_size: 2
num_workers: 16

#NOTE: Not sure what it is.
transparent: true 

deepspeed: true
distributed_backend: true

# Dataset Settings
DATASET:
  train_dataset: 'action_nturgbd'
  test_dataset: 'action_nturgbd'
  root: '/mnt/DATASETS_RAID_28TB/nturgbd/'
  window_size: &dws 300 # Dataset Window Size
  frame_interval: 1
  stride: 1
  joint_req: 0.9
  test_subset: 'X_sub_val' # X_setup_val X_sub_val
  train_subset: 'X_sub_train' # # X_setup_train X_sub_train
  camera_num: 10
  training_mode: 'fine-tuning'
  resolution: [1920, 1080]
  num_classes: 120
  drop_frames_rate: 0.3
  # Some of the NTU video have just around 1 second.
  max_num_frame_rate: 0.9
  linear_interpolate: True
  second_heatmap_size: &dVAE_heatmap_size null


  # Heatmap Generator
  Heatmap_Generator:
    use_gaussian_score: false
    with_limb: true
    with_kp: false
    heatmap_size: &hms 256 # Heatmap Size
    scaling: 1.0


# Model Settings
ImageEmbed:
  image_size: *hms
  num_layers: 3 # Number of layers (should be 3 or above)
  num_tokens: 8192 # Number of image tokens
  hidden_dim: 256
  num_resnet_blocks: 4 # Number of residual net blocks
  normalization: null
  use_SiLU: True
  temperature: 0.9
  straight_through: false

Pretrained_Models:
  discrete_vae_weight_path: './saved_models/vae_300_panoptic_cheerful-goat-7.pt'
  pretrain_saved_file: './saved_models/beit_best_incandescent-laughter-7.pt'


PeIT:
  finetune_saved_file: ''
  window_size:
    - 0
    - 0
  num_mask_patches: 204
  max_mask_patches_per_block: null
  min_mask_patches_per_block: 16